// ═══════════════════════════════════════════════════════════
// STICKER DATABASE
// Each entry: { id, name, team, holo }
// holo: true for emblem stickers (= hologram parallels)
// ═══════════════════════════════════════════════════════════
// ═══════════════════════════════════════════════════════════
// WORLD CUP 2026 GROUPS (sorted by draw)
// ═══════════════════════════════════════════════════════════
const WC_GROUPS = [
  { name: 'Copa del Mundo', teams: ['FWC_INTRO'] },
  { name: 'Grupo A', teams: ['MEX','RSA','KOR','CZE'] },
  { name: 'Grupo B', teams: ['CAN','BIH','QAT','SUI'] },
  { name: 'Grupo C', teams: ['BRA','MAR','HAI','SCO'] },
  { name: 'Grupo D', teams: ['USA','PAR','AUS','TUR'] },
  { name: 'Grupo E', teams: ['GER','CUW','CIV','ECU'] },
  { name: 'Grupo F', teams: ['NED','JPN','SWE','TUN'] },
  { name: 'Grupo G', teams: ['BEL','EGY','IRN','NZL'] },
  { name: 'Grupo H', teams: ['ESP','CPV','KSA','URU'] },
  { name: 'Grupo I', teams: ['FRA','SEN','IRQ','NOR'] },
  { name: 'Grupo J', teams: ['ARG','ALG','AUT','JOR'] },
  { name: 'Grupo K', teams: ['POR','COD','UZB','COL'] },
  { name: 'Grupo L', teams: ['ENG','CRO','GHA','PAN'] },
  { name: 'Especiales', teams: ['FWC'] },
  { name: 'Coca-Cola', teams: ['CC'] },
];

const TEAMS = [
  { key:'00',  label:'🌟 We Are Panini' },
  { key:'FWC_INTRO', label:'🏆 FWC · FIFA World Cup 2026' },
  { key:'FWC', label:'🏆 FWC · FIFA World Cup History' },
  { key:'CC',  label:'🥤 CC · Coca-Cola (Latin America)' },
  { key:'ALG', label:'🇩🇿 ALG · Algeria' },
  { key:'ARG', label:'🇦🇷 ARG · Argentina' },
  { key:'AUS', label:'🇦🇺 AUS · Australia' },
  { key:'AUT', label:'🇦🇹 AUT · Austria' },
  { key:'BEL', label:'🇧🇪 BEL · Belgium' },
  { key:'BIH', label:'🇧🇦 BIH · Bosnia and Herzegovina' },
  { key:'BRA', label:'🇧🇷 BRA · Brazil' },
  { key:'CAN', label:'🇨🇦 CAN · Canada' },
  { key:'CIV', label:'🇨🇮 CIV · Ivory Coast' },
  { key:'COD', label:'🇨🇩 COD · Congo DR' },
  { key:'COL', label:'🇨🇴 COL · Colombia' },
  { key:'CPV', label:'🇨🇻 CPV · Cape Verde' },
  { key:'CRO', label:'🇭🇷 CRO · Croatia' },
  { key:'CUW', label:'🇨🇼 CUW · Curaçao' },
  { key:'CZE', label:'🇨🇿 CZE · Czechia' },
  { key:'ECU', label:'🇪🇨 ECU · Ecuador' },
  { key:'EGY', label:'🇪🇬 EGY · Egypt' },
  { key:'ENG', label:'🏴󠁧󠁢󠁥󠁮󠁧󠁿 ENG · England' },
  { key:'ESP', label:'🇪🇸 ESP · Spain' },
  { key:'FRA', label:'🇫🇷 FRA · France' },
  { key:'GER', label:'🇩🇪 GER · Germany' },
  { key:'GHA', label:'🇬🇭 GHA · Ghana' },
  { key:'HAI', label:'🇭🇹 HAI · Haiti' },
  { key:'IRN', label:'🇮🇷 IRN · Iran' },
  { key:'IRQ', label:'🇮🇶 IRQ · Iraq' },
  { key:'JOR', label:'🇯🇴 JOR · Jordan' },
  { key:'JPN', label:'🇯🇵 JPN · Japan' },
  { key:'KOR', label:'🇰🇷 KOR · Korea Republic' },
  { key:'KSA', label:'🇸🇦 KSA · Saudi Arabia' },
  { key:'MAR', label:'🇲🇦 MAR · Morocco' },
  { key:'MEX', label:'🇲🇽 MEX · Mexico' },
  { key:'NED', label:'🇳🇱 NED · Netherlands' },
  { key:'NOR', label:'🇳🇴 NOR · Norway' },
  { key:'NZL', label:'🇳🇿 NZL · New Zealand' },
  { key:'PAN', label:'🇵🇦 PAN · Panama' },
  { key:'PAR', label:'🇵🇾 PAR · Paraguay' },
  { key:'POR', label:'🇵🇹 POR · Portugal' },
  { key:'QAT', label:'🇶🇦 QAT · Qatar' },
  { key:'RSA', label:'🇿🇦 RSA · South Africa' },
  { key:'SCO', label:'🏴󠁧󠁢󠁳󠁣󠁴󠁿 SCO · Scotland' },
  { key:'SEN', label:'🇸🇳 SEN · Senegal' },
  { key:'SUI', label:'🇨🇭 SUI · Switzerland' },
  { key:'SWE', label:'🇸🇪 SWE · Sweden' },
  { key:'TUN', label:'🇹🇳 TUN · Tunisia' },
  { key:'TUR', label:'🇹🇷 TUR · Türkiye' },
  { key:'URU', label:'🇺🇾 URU · Uruguay' },
  { key:'USA', label:'🇺🇸 USA · United States' },
  { key:'UZB', label:'🇺🇿 UZB · Uzbekistan' },
];

function S(id, name, holo=false){ return {id, name, holo}; }
function team(stickers){ return stickers; }

const STICKERS_BY_TEAM = {
  'FWC_INTRO': [
    S('00','We Are Panini',true),
    S('FWC-1','Official Emblem 1/2',true), S('FWC-2','Official Emblem 2/2',true),
    S('FWC-3','Official Mascots'), S('FWC-4','Official Slogan'), S('FWC-5','Official Ball'),
    S('FWC-6','Canada (Host Country)',true), S('FWC-7','Mexico (Host Country)',true), S('FWC-8','USA (Host Country)',true),
  ],
  'FWC': [
    S('FWC-9','FWC-9'), S('FWC-10','FWC-10'), S('FWC-11','FWC-11'),
    S('FWC-12','FWC-12'), S('FWC-13','FWC-13'), S('FWC-14','FWC-14'),
    S('FWC-15','FWC-15'), S('FWC-16','FWC-16'), S('FWC-17','FWC-17'),
    S('FWC-18','FWC-18'), S('FWC-19','FWC-19'),
  ],
  'CC': [
    S('CC1','Lamine Yamal (Spain)'), S('CC2','Joshua Kimmich (Germany)'), S('CC3','Harry Kane (England)'),
    S('CC4','Santiago Giménez (Mexico)'), S('CC5','Josko Gvardiol (Croatia)'), S('CC6','Federico Valverde (Uruguay)'),
    S('CC7','Jefferson Lerma (Colombia)'), S('CC8','Enner Valencia (Ecuador)'), S('CC9','Gabriel Magalhães (Brazil)'),
    S('CC10','Virgil van Dijk (Netherlands)'), S('CC11','Alphonso Davies (Canada)'), S('CC12','Emiliano Martinez (Argentina)'),
    S('CC13','Raúl Jiménez (Mexico)'), S('CC14','Lautaro Martínez (Argentina)'),
  ],
  'ALG': [
    S('ALG-1','Emblem',true), S('ALG-2','Alexis Guendouz'), S('ALG-3','Ramy Bensebaini'), S('ALG-4','Youcef Atal'),
    S('ALG-5','Rayan Aït-Nouri'), S('ALG-6','Mohamed Amine Tougai'), S('ALG-7','Aïssa Mandi'), S('ALG-8','Ismael Bennacer'),
    S('ALG-9','Houssem Aquar'), S('ALG-10','Hicham Boudaoui'), S('ALG-11','Ramiz Zerrouki'), S('ALG-12','Nabil Bentalab'),
    S('ALG-13','Team Photo'), S('ALG-14','Farés Chaibi'), S('ALG-15','Riyad Mahrez'), S('ALG-16','Said Benrhama'),
    S('ALG-17','Anis Hadj Moussa'), S('ALG-18','Amine Gouiri'), S('ALG-19','Baghdad Bounedjah'), S('ALG-20','Mohammed Amoura'),
  ],
  'ARG': [
    S('ARG-1','Emblem',true), S('ARG-2','Emiliano Martinez'), S('ARG-3','Nahuel Molina'), S('ARG-4','Cristian Romero'),
    S('ARG-5','Nicolas Otamendi'), S('ARG-6','Nicolas Tagliafico'), S('ARG-7','Leonardo Balerdi'), S('ARG-8','Enzo Fernandez'),
    S('ARG-9','Alexis Mac Allister'), S('ARG-10','Rodrigo De Paul'), S('ARG-11','Exequiel Palacios'), S('ARG-12','Leandro Paredes'),
    S('ARG-13','Team Photo'), S('ARG-14','Nico Paz'), S('ARG-15','Franco Mastantuono'), S('ARG-16','Nico Gonzalez'),
    S('ARG-17','Lionel Messi'), S('ARG-18','Lautaro Martinez'), S('ARG-19','Julian Alvarez'), S('ARG-20','Giuliano Simeone'),
  ],
  'AUS': [
    S('AUS-1','Emblem',true), S('AUS-2','Mathew Ryan'), S('AUS-3','Joe Gauci'), S('AUS-4','Harry Souttar'),
    S('AUS-5','Alessandro Circati'), S('AUS-6','Jordan Bos'), S('AUS-7','Aziz Behich'), S('AUS-8','Cameron Burgess'),
    S('AUS-9','Lewis Miller'), S('AUS-10','Milos Degenek'), S('AUS-11','Jackson Irvine'), S('AUS-12','Riley McGree'),
    S('AUS-13','Team Photo'), S('AUS-14','Aiden O\'Neill'), S('AUS-15','Connor Metcalfe'), S('AUS-16','Patrick Yazbek'),
    S('AUS-17','Craig Goodwin'), S('AUS-18','Kusini Vengi'), S('AUS-19','Nestory Irankunda'), S('AUS-20','Mohamed Touré'),
  ],
  'AUT': [
    S('AUT-1','Emblem',true), S('AUT-2','Alexander Schlager'), S('AUT-3','Patrick Pentz'), S('AUT-4','David Alaba'),
    S('AUT-5','Kevin Danso'), S('AUT-6','Philipp Lienhart'), S('AUT-7','Stefan Bosch'), S('AUT-8','Phillipp Mwene'),
    S('AUT-9','Alexander Prass'), S('AUT-10','Xavier Schlager'), S('AUT-11','Marcel Sabitzer'), S('AUT-12','Konrad Laimer'),
    S('AUT-13','Team Photo'), S('AUT-14','Florian Grillitsch'), S('AUT-15','Nicolas Seiwald'), S('AUT-16','Romano Schmid'),
    S('AUT-17','Patrick Wimmer'), S('AUT-18','Christoph Baumgartner'), S('AUT-19','Michael Gregoritsch'), S('AUT-20','Marko Arnautović'),
  ],
  'BEL': [
    S('BEL-1','Emblem',true), S('BEL-2','Thibaut Courtois'), S('BEL-3','Arthur Theate'), S('BEL-4','Timothy Castagne'),
    S('BEL-5','Zeno Debast'), S('BEL-6','Brandon Mechele'), S('BEL-7','Maxim De Cuyper'), S('BEL-8','Thomas Meunier'),
    S('BEL-9','Youri Tieleman'), S('BEL-10','Amadou Onana'), S('BEL-11','Nicolas Raskin'), S('BEL-12','Alexis Saelemaekers'),
    S('BEL-13','Team Photo'), S('BEL-14','Hans Vanaken'), S('BEL-15','Kevin De Bruyne'), S('BEL-16','Jérémy Doku'),
    S('BEL-17','Charles De Ketelaere'), S('BEL-18','Leandro Trossard'), S('BEL-19','Loïs Openda'), S('BEL-20','Romelu Lukaku'),
  ],
  'BIH': [
    S('BIH-1','Emblem',true), S('BIH-2','Nikola Vasilj'), S('BIH-3','Amer Dedic'), S('BIH-4','Sead Kolasinac'),
    S('BIH-5','Tarik Muharemovic'), S('BIH-6','Nihad Mujakic'), S('BIH-7','Nikola Katic'), S('BIH-8','Amir Hadziahmetovic'),
    S('BIH-9','Benjamin Tahirovic'), S('BIH-10','Armin Gigovic'), S('BIH-11','Ivan Sunjic'), S('BIH-12','Ivan Basic'),
    S('BIH-13','Team Photo'), S('BIH-14','Dzenis Burnic'), S('BIH-15','Esmir Bajraktarevic'), S('BIH-16','Amar Memic'),
    S('BIH-17','Ermedin Demirovic'), S('BIH-18','Edin Dzeko'), S('BIH-19','Samed Bazdar'), S('BIH-20','Haris Tabakovic'),
  ],
  'BRA': [
    S('BRA-1','Emblem',true), S('BRA-2','Alisson'), S('BRA-3','Bento'), S('BRA-4','Marquinhos'),
    S('BRA-5','Éder Militão'), S('BRA-6','Gabriel Magalhães'), S('BRA-7','Danilo'), S('BRA-8','Wesley'),
    S('BRA-9','Lucas Paquetá'), S('BRA-10','Casemiro'), S('BRA-11','Bruno Guimarães'), S('BRA-12','Luiz Henrique'),
    S('BRA-13','Team Photo'), S('BRA-14','Vinicius Júnior'), S('BRA-15','Rodrygo'), S('BRA-16','João Pedro'),
    S('BRA-17','Matheus Cunha'), S('BRA-18','Gabriel Martinelli'), S('BRA-19','Raphinha'), S('BRA-20','Estévão'),
  ],
  'CAN': [
    S('CAN-1','Emblem',true), S('CAN-2','Dayne St.Clair'), S('CAN-3','Alphonso Davies'), S('CAN-4','Alistair Johnston'),
    S('CAN-5','Samuel Adekugbe'), S('CAN-6','Riche Larvea'), S('CAN-7','Derek Cornelius'), S('CAN-8','Moïse Bombito'),
    S('CAN-9','Kamal Miller'), S('CAN-10','Stephen Eustáquio'), S('CAN-11','Ismaël Koné'), S('CAN-12','Jonathan Osorio'),
    S('CAN-13','Team Photo'), S('CAN-14','Jacob Shaffelburg'), S('CAN-15','Mathieu Choinière'), S('CAN-16','Niko Sigur'),
    S('CAN-17','Tajon Buchanan'), S('CAN-18','Liam Millar'), S('CAN-19','Cyle Larin'), S('CAN-20','Jonathan David'),
  ],
  'CIV': [
    S('CIV-1','Emblem',true), S('CIV-2','Yahia Fofana'), S('CIV-3','Ghislain Konan'), S('CIV-4','Wilfried Singo'),
    S('CIV-5','Odilon Kossounou'), S('CIV-6','Evan Ndicka'), S('CIV-7','Willy Boly'), S('CIV-8','Emmanuel Agbadou'),
    S('CIV-9','Ousmane Diomande'), S('CIV-10','Franck Kessie'), S('CIV-11','Seko Fofana'), S('CIV-12','Ibrahim Sangare'),
    S('CIV-13','Team Photo'), S('CIV-14','Jean-Philippe Gbamin'), S('CIV-15','Amad Diallo'), S('CIV-16','Sébastien Haller'),
    S('CIV-17','Simon Adringa'), S('CIV-18','Yan Diomande'), S('CIV-19','Evann Guessand'), S('CIV-20','Oumar Diakite'),
  ],
  'COD': [
    S('COD-1','Emblem',true), S('COD-2','Lionel Mpasi'), S('COD-3','Aaron Wan-Bissaka'), S('COD-4','Axel Tuanzebe'),
    S('COD-5','Arthur Masuaku'), S('COD-6','Chancel Mbemba'), S('COD-7','Joris Kayembe'), S('COD-8','Charles Pickel'),
    S('COD-9','Ngal\'ayel Mukau'), S('COD-10','Edo Kayembe'), S('COD-11','Samuel Moutoussamy'), S('COD-12','Noah Sadiki'),
    S('COD-13','Team Photo'), S('COD-14','Théo Bongonda'), S('COD-15','Meschak Elia'), S('COD-16','Yoane Wissa'),
    S('COD-17','Brian Cipenga'), S('COD-18','Fiston Mayele'), S('COD-19','Cédric Bakambu'), S('COD-20','Nathanaël Mbuku'),
  ],
  'COL': [
    S('COL-1','Emblem',true), S('COL-2','Camilo Vargas'), S('COL-3','David Ospina'), S('COL-4','Dávinson Sánchez'),
    S('COL-5','Yerry Mina'), S('COL-6','Daniel Munoz'), S('COL-7','Johan Mojica'), S('COL-8','Jhon Lucumí'),
    S('COL-9','Santiago Arias'), S('COL-10','Jefferson Lerma'), S('COL-11','Kevin Castaño'), S('COL-12','Richard Rios'),
    S('COL-13','Team Photo'), S('COL-14','James Rodriguez'), S('COL-15','Juan Fernando Quintero'), S('COL-16','Jorge Carrascal'),
    S('COL-17','Jon Arias'), S('COL-18','Jhon Cordova'), S('COL-19','Luis Suarez'), S('COL-20','Luis Diaz'),
  ],
  'CPV': [
    S('CPV-1','Emblem',true), S('CPV-2','Vozinha'), S('CPV-3','Logan Costa'), S('CPV-4','Pico'),
    S('CPV-5','Diney'), S('CPV-6','Steven Moreira'), S('CPV-7','Wagner Pina'), S('CPV-8','Joao Paulo'),
    S('CPV-9','Yannick Semedo'), S('CPV-10','Kevin Pina'), S('CPV-11','Patrick Andrade'), S('CPV-12','Jamiro Monteiro'),
    S('CPV-13','Team Photo'), S('CPV-14','Deroy Duarte'), S('CPV-15','Garry Rodrigues'), S('CPV-16','Jovane Cabral'),
    S('CPV-17','Ryan Mendes'), S('CPV-18','Dailon Livramento'), S('CPV-19','Willy Semedo'), S('CPV-20','Bebe'),
  ],
  'CRO': [
    S('CRO-1','Emblem',true), S('CRO-2','Dominik Livaković'), S('CRO-3','Duje Caleta-Car'), S('CRO-4','Josko Gvardiol'),
    S('CRO-5','Josip Stanišić'), S('CRO-6','Luka Vušković'), S('CRO-7','Josip Sutalo'), S('CRO-8','Kristijan Jakic'),
    S('CRO-9','Luka Modrić'), S('CRO-10','Mateo Kovacic'), S('CRO-11','Martin Baturina'), S('CRO-12','Lovro Majer'),
    S('CRO-13','Team Photo'), S('CRO-14','Mario Pasalic'), S('CRO-15','Petar Sucic'), S('CRO-16','Ivan Perišić'),
    S('CRO-17','Marco Pasalic'), S('CRO-18','Ante Budimir'), S('CRO-19','Andrej Kramarić'), S('CRO-20','Franjo Ivanovic'),
  ],
  'CUW': [
    S('CUW-1','Emblem',true), S('CUW-2','Eloy Room'), S('CUW-3','Armando Obispo'), S('CUW-4','Sherel Floranus'),
    S('CUW-5','Jurien Gaari'), S('CUW-6','Joshua Brenet'), S('CUW-7','Roshon Van Eijma'), S('CUW-8','Shurandy Sambo'),
    S('CUW-9','Livano Comenencia'), S('CUW-10','Godfried Roemeratoe'), S('CUW-11','Juninho Bacuna'), S('CUW-12','Leandro Bacuna'),
    S('CUW-13','Team Photo'), S('CUW-14','Tahith Chong'), S('CUW-15','Kenji Gorre'), S('CUW-16','Jearl Margaritha'),
    S('CUW-17','Jurgen Locadia'), S('CUW-18','Jeremy Antonisse'), S('CUW-19','Gervane Kastaneer'), S('CUW-20','Sontje Hansen'),
  ],
  'CZE': [
    S('CZE-1','Emblem',true), S('CZE-2','Matej Kovar'), S('CZE-3','Jindrich Stanek'), S('CZE-4','Ladislav Krejci'),
    S('CZE-5','Vladimir Coufal'), S('CZE-6','Jaroslav Zeleny'), S('CZE-7','Tomas Holes'), S('CZE-8','David Zima'),
    S('CZE-9','Michal Sadilek'), S('CZE-10','Lukas Provod'), S('CZE-11','Lukas Cerv'), S('CZE-12','Tomas Soucek'),
    S('CZE-13','Team Photo'), S('CZE-14','Pavel Sulc'), S('CZE-15','Matej Vydra'), S('CZE-16','Vasil Kusej'),
    S('CZE-17','Tomas Chory'), S('CZE-18','Vacilav Cerny'), S('CZE-19','Adam Hlozek'), S('CZE-20','Patrik Schick'),
  ],
  'ECU': [
    S('ECU-1','Emblem',true), S('ECU-2','Hernán Galíndez'), S('ECU-3','Gonzalo Valle'), S('ECU-4','Piero Hincapié'),
    S('ECU-5','Pervis Estupiñán'), S('ECU-6','Willian Pacho'), S('ECU-7','Ángelo Preciado'), S('ECU-8','Joel Ordóñez'),
    S('ECU-9','Moises Caicedo'), S('ECU-10','Alan Franco'), S('ECU-11','Kendry Paez'), S('ECU-12','Pedro Vite'),
    S('ECU-13','Team Photo'), S('ECU-14','John Veboah'), S('ECU-15','Leonardo Campana'), S('ECU-16','Gonzalo Plata'),
    S('ECU-17','Nilson Angulo'), S('ECU-18','Alan Minda'), S('ECU-19','Kevin Rodriguez'), S('ECU-20','Enner Valencia'),
  ],
  'EGY': [
    S('EGY-1','Emblem',true), S('EGY-2','Mohamed El Shenawy'), S('EGY-3','Mohamed Hany'), S('EGY-4','Mohamed Hamdy'),
    S('EGY-5','Yasser Ibrahim'), S('EGY-6','Khaled Sobhi'), S('EGY-7','Ramy Rabia'), S('EGY-8','Hossam Abdelmaguid'),
    S('EGY-9','Ahmed Fatouh'), S('EGY-10','Marwan Attia'), S('EGY-11','Zizo'), S('EGY-12','Hamdy Fathy'),
    S('EGY-13','Team Photo'), S('EGY-14','Mohamed Lasheen'), S('EGY-15','Emam Ashour'), S('EGY-16','Osama Faisal'),
    S('EGY-17','Mohamed Salah'), S('EGY-18','Mostafa Mohamed'), S('EGY-19','Trezeguet'), S('EGY-20','Omar Marsmoush'),
  ],
  'ENG': [
    S('ENG-1','Emblem',true), S('ENG-2','Jordan Pickford'), S('ENG-3','John Stones'), S('ENG-4','Maric Guéhi'),
    S('ENG-5','Ezri Konsa'), S('ENG-6','Trent Alexander-Arnold'), S('ENG-7','Reece James'), S('ENG-8','Dan Burn'),
    S('ENG-9','Jordan Henderson'), S('ENG-10','Declan Rice'), S('ENG-11','Jude Bellingham'), S('ENG-12','Cole Palmer'),
    S('ENG-13','Team Photo'), S('ENG-14','Morgan Rogers'), S('ENG-15','Anthony Gordon'), S('ENG-16','Phil Foden'),
    S('ENG-17','Bukayo Saka'), S('ENG-18','Harry Kane'), S('ENG-19','Marcus Rashford'), S('ENG-20','Ollie Watkins'),
  ],
  'ESP': [
    S('ESP-1','Emblem',true), S('ESP-2','Unai Simon'), S('ESP-3','Robin Le Normand'), S('ESP-4','Aymeric Laporte'),
    S('ESP-5','Dean Huijsen'), S('ESP-6','Pedro Porro'), S('ESP-7','Dani Carvajal'), S('ESP-8','Marc Cucurella'),
    S('ESP-9','Martín Zubimendi'), S('ESP-10','Rodri'), S('ESP-11','Pedri'), S('ESP-12','Fabian Ruiz'),
    S('ESP-13','Team Photo'), S('ESP-14','Mikel Merino'), S('ESP-15','Lamine Yamal'), S('ESP-16','Dani Olmo'),
    S('ESP-17','Nico Williams'), S('ESP-18','Ferran Torres'), S('ESP-19','Álvaro Morata'), S('ESP-20','Mikel Oyarzabal'),
  ],
  'FRA': [
    S('FRA-1','Emblem',true), S('FRA-2','Mike Maignan'), S('FRA-3','Theo Hernandez'), S('FRA-4','William Saliba'),
    S('FRA-5','Jules Kounde'), S('FRA-6','Ibrahima Konate'), S('FRA-7','Dayot Upamecano'), S('FRA-8','Lucas Digne'),
    S('FRA-9','Aurélien Tchouaméni'), S('FRA-10','Eduardo Camavinga'), S('FRA-11','Manu Kone'), S('FRA-12','Adrien Rabiot'),
    S('FRA-13','Team Photo'), S('FRA-14','Michael Olise'), S('FRA-15','Ousmane Dembele'), S('FRA-16','Bradley Barcola'),
    S('FRA-17','Désiré Doué'), S('FRA-18','Kingsley Coman'), S('FRA-19','Hugo Ekitike'), S('FRA-20','Kylian Mbappe'),
  ],
  'GER': [
    S('GER-1','Emblem',true), S('GER-2','Marc-André ter Stegen'), S('GER-3','Jonathan Tah'), S('GER-4','David Raum'),
    S('GER-5','Nico Schlotterbeck'), S('GER-6','Antonio Rüdiger'), S('GER-7','Waldemar Anton'), S('GER-8','Ridle Baku'),
    S('GER-9','Maximilian Mittelstadt'), S('GER-10','Joshua Kimmich'), S('GER-11','Florian Wirtz'), S('GER-12','Felix Nmecha'),
    S('GER-13','Team Photo'), S('GER-14','Leon Goretzka'), S('GER-15','Jamal Musiala'), S('GER-16','Serge Gnabry'),
    S('GER-17','Kai Havertz'), S('GER-18','Leroy Sane'), S('GER-19','Karim Adeyemi'), S('GER-20','Nick Woltemade'),
  ],
  'GHA': [
    S('GHA-1','Emblem',true), S('GHA-2','Lawrence Ati Zigi'), S('GHA-3','Tariq Lamptey'), S('GHA-4','Mohammed Salisu'),
    S('GHA-5','Alidu Seidu'), S('GHA-6','Alexander Djiku'), S('GHA-7','Gideon Mensah'), S('GHA-8','Caleb Yirenkyi'),
    S('GHA-9','Abdul Issahaku Fatawu'), S('GHA-10','Thomas Partey'), S('GHA-11','Salis Abdul Samed'), S('GHA-12','Kamaldeen Sulemana'),
    S('GHA-13','Team Photo'), S('GHA-14','Mohammed Kudus'), S('GHA-15','Inaki Williams'), S('GHA-16','Jordan Ayew'),
    S('GHA-17','Andrew Ayew'), S('GHA-18','Joseph Paintsil'), S('GHA-19','Osman Bukari'), S('GHA-20','Antoine Semenyo'),
  ],
  'HAI': [
    S('HAI-1','Emblem',true), S('HAI-2','Johny Placide'), S('HAI-3','Carlens Arcus'), S('HAI-4','Martin Expérience'),
    S('HAI-5','Jean-Kevin Duverne'), S('HAI-6','Ricardo Adé'), S('HAI-7','Duke Lacroix'), S('HAI-8','Garven Metusala'),
    S('HAI-9','Hannes Delcroix'), S('HAI-10','Leverton Pierre'), S('HAI-11','Danley Jean Jacques'), S('HAI-12','Jean-Ricner Bellegarde'),
    S('HAI-13','Team Photo'), S('HAI-14','Christopher Attys'), S('HAI-15','Derrick Etienne Jr.'), S('HAI-16','Josue Casimir'),
    S('HAI-17','Ruben Providence'), S('HAI-18','Duckens Nazon'), S('HAI-19','Louicius Deedson'), S('HAI-20','Frantzdy Pierrot'),
  ],
  'IRN': [
    S('IRN-1','Emblem',true), S('IRN-2','Alirez Beiranvand'), S('IRN-3','Morteza Pouraliganji'), S('IRN-4','Ehsan Hajsafi'),
    S('IRN-5','Milad Mohammadi'), S('IRN-6','Shojae Khalilzadeh'), S('IRN-7','Ramin Rezaeian'), S('IRN-8','Hossein Kanaani'),
    S('IRN-9','Sadegh Moharrami'), S('IRN-10','Saleh Hardani'), S('IRN-11','Saeed Ezatolahi'), S('IRN-12','Saman Ghoddos'),
    S('IRN-13','Team Photo'), S('IRN-14','Omid Noorafkan'), S('IRN-15','Roozbeh Cheshmi'), S('IRN-16','Mohammad Mohebi'),
    S('IRN-17','Sardar Azmoun'), S('IRN-18','Mehdi Taremi'), S('IRN-19','Alireza Jahanbakhsh'), S('IRN-20','Ali Gholizadeh'),
  ],
  'IRQ': [
    S('IRQ-1','Emblem',true), S('IRQ-2','Jalal Hassan'), S('IRQ-3','Rebin Sulaka'), S('IRQ-4','Hussein Ali'),
    S('IRQ-5','Akam Hashem'), S('IRQ-6','Merchas Doski'), S('IRQ-7','Zaid Tahseen'), S('IRQ-8','Manaf Younis'),
    S('IRQ-9','Zidane Iqbal'), S('IRQ-10','Amir Al-Ammari'), S('IRQ-11','Ibrahim Bavesh'), S('IRQ-12','Ali Jasim'),
    S('IRQ-13','Team Photo'), S('IRQ-14','Youssef Amyn'), S('IRQ-15','Aimar Sher'), S('IRQ-16','Marko Farji'),
    S('IRQ-17','Osama Rashid'), S('IRQ-18','Ali Al-Hamadi'), S('IRQ-19','Aymen Hussein'), S('IRQ-20','Mohanad Ali'),
  ],
  'JOR': [
    S('JOR-1','Emblem',true), S('JOR-2','Yazeed Abulaila'), S('JOR-3','Ihsan Haddad'), S('JOR-4','Mohammad Abu Hashish'),
    S('JOR-5','Yazan Al-Arab'), S('JOR-6','Abdallah Nasib'), S('JOR-7','Saleem Obaid'), S('JOR-8','Mohammad Abualnadi'),
    S('JOR-9','Ibrahim Saadeh'), S('JOR-10','Nizar Al-Rashdan'), S('JOR-11','Noor Al-Rawabdeh'), S('JOR-12','Mohannad Abu Taha'),
    S('JOR-13','Team Photo'), S('JOR-14','Amer Jamous'), S('JOR-15','Musa Al-Taamari'), S('JOR-16','Yazan Al-Naimat'),
    S('JOR-17','Mahmoud Al-Mardi'), S('JOR-18','Ali Olwan'), S('JOR-19','Mohammad Abu Zrayq'), S('JOR-20','Ibrahim Sabra'),
  ],
  'JPN': [
    S('JPN-1','Emblem',true), S('JPN-2','Zion Suzuki'), S('JPN-3','Henry Heroki Mochizuki'), S('JPN-4','Ayumu Seko'),
    S('JPN-5','Junnosuke Suzuki'), S('JPN-6','Shogo Taniguchi'), S('JPN-7','Tsuyoshi Watanabe'), S('JPN-8','Kaishu Sano'),
    S('JPN-9','Yuki Soma'), S('JPN-10','Ao Tanaka'), S('JPN-11','Daichi Kamada'), S('JPN-12','Takefusa Kubo'),
    S('JPN-13','Team Photo'), S('JPN-14','Ritsu Doan'), S('JPN-15','Keito Nakamura'), S('JPN-16','Takumi Minamino'),
    S('JPN-17','Shuto Machino'), S('JPN-18','Junya Ito'), S('JPN-19','Koki Ogawa'), S('JPN-20','Ayase Ueda'),
  ],
  'KOR': [
    S('KOR-1','Emblem',true), S('KOR-2','Hyeon-woo Jo'), S('KOR-3','Seung-Gyu Kim'), S('KOR-4','Min-jae Kim'),
    S('KOR-5','Yu-min Cho'), S('KOR-6','Young-woo Seol'), S('KOR-7','Han-beom Lee'), S('KOR-8','Tae-seok Lee'),
    S('KOR-9','Myung-jae Lee'), S('KOR-10','Jae-sung Lee'), S('KOR-11','In-beom Hwang'), S('KOR-12','Kang-in Lee'),
    S('KOR-13','Team Photo'), S('KOR-14','Seung-ho Paik'), S('KOR-15','Jens Castrop'), S('KOR-16','Dongg-yeong Lee'),
    S('KOR-17','Gue-sung Cho'), S('KOR-18','Heung-min Son'), S('KOR-19','Hee-chan Hwang'), S('KOR-20','Hyeon-Gyu Oh'),
  ],
  'KSA': [
    S('KSA-1','Emblem',true), S('KSA-2','Nawaf Alaqidi'), S('KSA-3','Abdulrahman Al-Sanbi'), S('KSA-4','Saud Abdulhamid'),
    S('KSA-5','Nawaf Bouwashl'), S('KSA-6','Jihad Thakri'), S('KSA-7','Moteb Al-Harbi'), S('KSA-8','Hassan Altambakti'),
    S('KSA-9','Musab Aljuwayr'), S('KSA-10','Ziyad Aljohani'), S('KSA-11','Abdullah Alkhaibari'), S('KSA-12','Nasser Aldawsari'),
    S('KSA-13','Team Photo'), S('KSA-14','Saleh Abu Alshamat'), S('KSA-15','Marwan Alsahafi'), S('KSA-16','Salem Aldawsari'),
    S('KSA-17','Abdulrahman Al-Aboud'), S('KSA-18','Feras Akbrikan'), S('KSA-19','Saleh Alshehri'), S('KSA-20','Abdullah Al-Hamdan'),
  ],
  'MAR': [
    S('MAR-1','Emblem',true), S('MAR-2','Yassine Bounou'), S('MAR-3','Munir El Kajoui'), S('MAR-4','Achraf Hakimi'),
    S('MAR-5','Noussair Mazraoui'), S('MAR-6','Nayef Aguerd'), S('MAR-7','Roman Saiss'), S('MAR-8','Jawad El Yamio'),
    S('MAR-9','Adam Masina'), S('MAR-10','Sofyan Amrabat'), S('MAR-11','Azzedine Ounahi'), S('MAR-12','Eliesse Ben Seghir'),
    S('MAR-13','Team Photo'), S('MAR-14','Bilal El Khannouss'), S('MAR-15','Ismael Saibari'), S('MAR-16','Youssef En-Nesyri'),
    S('MAR-17','Abde Ezzalzouli'), S('MAR-18','Soufiane Rahimi'), S('MAR-19','Brahim Diaz'), S('MAR-20','Ayoub El Kaabi'),
  ],
  'MEX': [
    S('MEX-1','Emblem',true), S('MEX-2','Luis Malagón'), S('MEX-3','Johan Vasquez'), S('MEX-4','Jorge Sánchez'),
    S('MEX-5','Cesar Montes'), S('MEX-6','Jesus Gallardo'), S('MEX-7','Israel Reyes'), S('MEX-8','Diego Lainez'),
    S('MEX-9','Carlos Rodriguez'), S('MEX-10','Edson Alvarez'), S('MEX-11','Orbelin Pineda'), S('MEX-12','Marcel Ruiz'),
    S('MEX-13','Team Photo'), S('MEX-14','Érick Sánchez'), S('MEX-15','Hirving Lozano'), S('MEX-16','Santiago Giménez'),
    S('MEX-17','Raúl Jiménez'), S('MEX-18','Alexis Vega'), S('MEX-19','Roberto Alvarado'), S('MEX-20','Cesar Huerta'),
  ],
  'NED': [
    S('NED-1','Emblem',true), S('NED-2','Bart Verbruggen'), S('NED-3','Virgil Van Dijk'), S('NED-4','Micky van de Ven'),
    S('NED-5','Jurien Timber'), S('NED-6','Denzel Dumfries'), S('NED-7','Nathan Aké'), S('NED-8','Jereme Frimpong'),
    S('NED-9','Jan Paul van Hecke'), S('NED-10','Tijjani Reijnders'), S('NED-11','Ryan Gravenberch'), S('NED-12','Teun Koopmeiners'),
    S('NED-13','Team Photo'), S('NED-14','Frenkie de Jong'), S('NED-15','Xavi Simons'), S('NED-16','Justin Kluivert'),
    S('NED-17','Memphis Depay'), S('NED-18','Donyell Malen'), S('NED-19','Wout Weghorst'), S('NED-20','Cody Gakpo'),
  ],
  'NOR': [
    S('NOR-1','Emblem',true), S('NOR-2','Orjan Nyland'), S('NOR-3','Julian Ryerson'), S('NOR-4','Leo Ostigård'),
    S('NOR-5','Kristoffer Vassbakk Ajer'), S('NOR-6','Marcus Holmgren Pedersen'), S('NOR-7','David Møller Wolfe'), S('NOR-8','Torbjørn Heggem'),
    S('NOR-9','Morten Thorsby'), S('NOR-10','Martin Ødegaard'), S('NOR-11','Sander Berge'), S('NOR-12','Andreas Schjelderup'),
    S('NOR-13','Team Photo'), S('NOR-14','Patrick Berg'), S('NOR-15','Erling Haaland'), S('NOR-16','Alexander Sørloth'),
    S('NOR-17','Aron Dønnum'), S('NOR-18','Jorgen Strand Larsen'), S('NOR-19','Antonio Nusa'), S('NOR-20','Oscar Bobb'),
  ],
  'NZL': [
    S('NZL-1','Emblem',true), S('NZL-2','Max Crocombe Payne'), S('NZL-3','Alex Paulsen'), S('NZL-4','Michael Boxall'),
    S('NZL-5','Liberato Cacace'), S('NZL-6','Tim Payne'), S('NZL-7','Tyler Bindon'), S('NZL-8','Francis de Vries'),
    S('NZL-9','Finn Surman'), S('NZL-10','Joe Bell'), S('NZL-11','Sarpreet Singh'), S('NZL-12','Ryan Thomas'),
    S('NZL-13','Team Photo'), S('NZL-14','Matthew Garbett'), S('NZL-15','Marko Stamenić'), S('NZL-16','Ben Old'),
    S('NZL-17','Chris Wood'), S('NZL-18','Elijah Just'), S('NZL-19','Callum McCowatt'), S('NZL-20','Kosta Barbarouses'),
  ],
  'PAN': [
    S('PAN-1','Emblem',true), S('PAN-2','Orlando Mosquera'), S('PAN-3','Luis Mejia'), S('PAN-4','Fidel Escobar'),
    S('PAN-5','Andres Andrade'), S('PAN-6','Michael Amir Murillo'), S('PAN-7','Eric Davis'), S('PAN-8','Jose Cordoba'),
    S('PAN-9','Cesar Blackman'), S('PAN-10','Cristian Martinez'), S('PAN-11','Aníbal Godoy'), S('PAN-12','Adalberto Carrasquilla'),
    S('PAN-13','Team Photo'), S('PAN-14','Édgar Bárcenas'), S('PAN-15','Carlos Harvey'), S('PAN-16','Ismael Díaz'),
    S('PAN-17','Jose Fajardo'), S('PAN-18','Cecilio Waterman'), S('PAN-19','Jose Luiz Rodriguez'), S('PAN-20','Alberto Quintero'),
  ],
  'PAR': [
    S('PAR-1','Emblem',true), S('PAR-2','Roberto Fernandez'), S('PAR-3','Orlando Gill'), S('PAR-4','Gustavo Gomez'),
    S('PAR-5','Fabián Balbuena'), S('PAR-6','Juan José Cáceres'), S('PAR-7','Omar Alderete'), S('PAR-8','Junior Alonso'),
    S('PAR-9','Mathías Villasanti'), S('PAR-10','Diego Gomez'), S('PAR-11','Damián Bobadilla'), S('PAR-12','Andres Cubas'),
    S('PAR-13','Team Photo'), S('PAR-14','Matias Galarza Fonda'), S('PAR-15','Julio Enciso'), S('PAR-16','Alejandro Romero Gamarra'),
    S('PAR-17','Miguel Almirón'), S('PAR-18','Ramon Sosa'), S('PAR-19','Angel Romero'), S('PAR-20','Antonio Sanabria'),
  ],
  'POR': [
    S('POR-1','Emblem',true), S('POR-2','Diogo Costa'), S('POR-3','Jose Sa'), S('POR-4','Ruben Dias'),
    S('POR-5','João Cancelaro'), S('POR-6','Diogo Dalot'), S('POR-7','Nuno Mendes'), S('POR-8','Gonçalo Inácio'),
    S('POR-9','Bernardo Silva'), S('POR-10','Bruno Fernandes'), S('POR-11','Ruben Neves'), S('POR-12','Vitinha'),
    S('POR-13','Team Photo'), S('POR-14','João Neves'), S('POR-15','Cristiano Ronaldo'), S('POR-16','Francisco Trincao'),
    S('POR-17','João Felix'), S('POR-18','Gonçalo Ramos'), S('POR-19','Pedro Neto'), S('POR-20','Rafael Leão'),
  ],
  'QAT': [
    S('QAT-1','Emblem',true), S('QAT-2','Meshaal Barsham'), S('QAT-3','Sultan Albrake'), S('QAT-4','Lucas Mendes'),
    S('QAT-5','Homam Ahmed'), S('QAT-6','Boualem Khoukhi'), S('QAT-7','Pedro Miguel'), S('QAT-8','Tarek Salman'),
    S('QAT-9','Mohamed Al-Mannai'), S('QAT-10','Karim Boudiaf'), S('QAT-11','Assim Madibo'), S('QAT-12','Ahmed Fatehi'),
    S('QAT-13','Team Photo'), S('QAT-14','Mohammed Waad'), S('QAT-15','Abdulaziz Hatem'), S('QAT-16','Hassan Al-Haydos'),
    S('QAT-17','Edmilson Junior'), S('QAT-18','Akram Hassan Afif'), S('QAT-19','Ahmed Al Ganehi'), S('QAT-20','Almoez Ali'),
  ],
  'RSA': [
    S('RSA-1','Emblem',true), S('RSA-2','Ronwen Williams'), S('RSA-3','Sipho Chaine'), S('RSA-4','Aubrey Modiba'),
    S('RSA-5','Samukele Kabini'), S('RSA-6','Mbekezeli Mbokazi'), S('RSA-7','Khulumani Ndamane'), S('RSA-8','Siyabonga Ngezana'),
    S('RSA-9','Khuliso Mudau'), S('RSA-10','Nkosinathi Sibisi'), S('RSA-11','Teboho Mokoena'), S('RSA-12','Thalente Mbatha'),
    S('RSA-13','Team Photo'), S('RSA-14','Bathasi Aubaas'), S('RSA-15','Yaya Sithole'), S('RSA-16','Sipho Mbule'),
    S('RSA-17','Lyle Foster'), S('RSA-18','Iqraam Rayners'), S('RSA-19','Mohau Nkota'), S('RSA-20','Oswin Appollis'),
  ],
  'SCO': [
    S('SCO-1','Emblem',true), S('SCO-2','Angus Gunn'), S('SCO-3','Jack Hendry'), S('SCO-4','Kieran Tierney'),
    S('SCO-5','Aaron Hickey'), S('SCO-6','Andrew Robertson'), S('SCO-7','Scott McKenna'), S('SCO-8','John Souttar'),
    S('SCO-9','Anthony Ralston'), S('SCO-10','Grant Hanley'), S('SCO-11','Scott McTominay'), S('SCO-12','Billy Gilmour'),
    S('SCO-13','Team Photo'), S('SCO-14','Lewis Ferguson'), S('SCO-15','Ryan Christie'), S('SCO-16','Kenny McLean'),
    S('SCO-17','John McGinn'), S('SCO-18','Lyndon Dykes'), S('SCO-19','Che Adams'), S('SCO-20','Ben Gannon-Doak'),
  ],
  'SEN': [
    S('SEN-1','Emblem',true), S('SEN-2','Eduardo Mendy'), S('SEN-3','Yehvann Diouf'), S('SEN-4','Moussa Niakhaté'),
    S('SEN-5','Abdoulaye Seck'), S('SEN-6','Ismail Jakobs'), S('SEN-7','El Hadji Malick Diouf'), S('SEN-8','Kalidou Koulibaly'),
    S('SEN-9','Idrissa Gana Gueye'), S('SEN-10','Pape Matar Sarr'), S('SEN-11','Pape Gueye'), S('SEN-12','Habib Diarra'),
    S('SEN-13','Team Photo'), S('SEN-14','Lamine Camara'), S('SEN-15','Sadio Mane'), S('SEN-16','Ismaïla Sarr'),
    S('SEN-17','Boulaye Dia'), S('SEN-18','Iliman Ndiaye'), S('SEN-19','Nicolas Jackson'), S('SEN-20','Krepin Diatta'),
  ],
  'SUI': [
    S('SUI-1','Emblem',true), S('SUI-2','Gregor Kobel'), S('SUI-3','Yvon Mvogo'), S('SUI-4','Manuel Akanji'),
    S('SUI-5','Ricardo Rodriguez'), S('SUI-6','Nico Elvedi'), S('SUI-7','Aurèle Amenda'), S('SUI-8','Silvan Widmer'),
    S('SUI-9','Granit Xhaka'), S('SUI-10','Denis Zakaria'), S('SUI-11','Remo Freuler'), S('SUI-12','Fabian Rieder'),
    S('SUI-13','Team Photo'), S('SUI-14','Ardon Jashari'), S('SUI-15','Johan Manzambi'), S('SUI-16','Michel Aebischer'),
    S('SUI-17','Breel Embolo'), S('SUI-18','Ruben Vargas'), S('SUI-19','Dan Ndoye'), S('SUI-20','Zeki Amdouni'),
  ],
  'SWE': [
    S('SWE-1','Emblem',true), S('SWE-2','Victor Johansson'), S('SWE-3','Isak Hien'), S('SWE-4','Gabriel Gudmundsson'),
    S('SWE-5','Emil Holm'), S('SWE-6','Victor Nilsson Lindelöf'), S('SWE-7','Gustaf Lagerbielke'), S('SWE-8','Lucas Bergvall'),
    S('SWE-9','Hugo Larsson'), S('SWE-10','Jesper Karlström'), S('SWE-11','Yasin Ayari'), S('SWE-12','Mattias Svanberg'),
    S('SWE-13','Team Photo'), S('SWE-14','Daniel Svensson'), S('SWE-15','Ken Sema'), S('SWE-16','Roony Bardghji'),
    S('SWE-17','Dejan Kulusevski'), S('SWE-18','Anthony Elanga'), S('SWE-19','Alexander Isak'), S('SWE-20','Viktor Gyökeres'),
  ],
  'TUN': [
    S('TUN-1','Emblem',true), S('TUN-2','Bechir Ben Said'), S('TUN-3','Aymen Dahmen'), S('TUN-4','Van Valery'),
    S('TUN-5','Montassar Talbi'), S('TUN-6','Yassine Meriah'), S('TUN-7','Ali Abdi'), S('TUN-8','Dylan Bronn'),
    S('TUN-9','Ellyes Skhiri'), S('TUN-10','Aissa Laidouni'), S('TUN-11','Ferjani Sassi'), S('TUN-12','Mohamed Ali Ben Romdhane'),
    S('TUN-13','Team Photo'), S('TUN-14','Hannibal Mejbri'), S('TUN-15','Elias Achouri'), S('TUN-16','Elias Saad'),
    S('TUN-17','Hazem Mastouri'), S('TUN-18','Ismael Gharbi'), S('TUN-19','Sayfallah Ltaief'), S('TUN-20','Naim Sliti'),
  ],
  'TUR': [
    S('TUR-1','Emblem',true), S('TUR-2','Ugurcan Cakir'), S('TUR-3','Mert Muldur'), S('TUR-4','Zeki Celik'),
    S('TUR-5','Abdulkerim Bardakci'), S('TUR-6','Caglar Soyunku'), S('TUR-7','Merih Demiral'), S('TUR-8','Ferdi Kadioglu'),
    S('TUR-9','Kaan Ayhan'), S('TUR-10','Ismail Yuksek'), S('TUR-11','Hakan Calhanoglu'), S('TUR-12','Orkun Kokcu'),
    S('TUR-13','Team Photo'), S('TUR-14','Arda Guler'), S('TUR-15','Irfan Can Kahvecu'), S('TUR-16','Yunus Akgun'),
    S('TUR-17','Can Uzun'), S('TUR-18','Baris Alper Yilmaz'), S('TUR-19','Kerem Akturkoglu'), S('TUR-20','Kenan Yildiz'),
  ],
  'URU': [
    S('URU-1','Emblem',true), S('URU-2','Sergio Rochet'), S('URU-3','Santiago Mele'), S('URU-4','Ronald Araujo'),
    S('URU-5','José María Giménez'), S('URU-6','Sebastian Caceres'), S('URU-7','Mathias Olivera'), S('URU-8','Guillermo Varela'),
    S('URU-9','Nahitan Nandez'), S('URU-10','Federico Valverde'), S('URU-11','Giorgian De Arrascaeta'), S('URU-12','Rodrigo Bentancur'),
    S('URU-13','Team Photo'), S('URU-14','Manuel Ugarte'), S('URU-15','Nicolás de la Cruz'), S('URU-16','Maxi Araujo'),
    S('URU-17','Darwin Núñez'), S('URU-18','Federico Viñas'), S('URU-19','Rodrigo Aguirre'), S('URU-20','Facundo Pellistri'),
  ],
  'USA': [
    S('USA-1','Emblem',true), S('USA-2','Matt Freese'), S('USA-3','Chris Richards'), S('USA-4','Tim Ream'),
    S('USA-5','Mark McKenzie'), S('USA-6','Alex Freeman'), S('USA-7','Antonee Robinson'), S('USA-8','Tyler Adams'),
    S('USA-9','Tanner Tessmann'), S('USA-10','Weston McKennie'), S('USA-11','Christian Roldan'), S('USA-12','Timothy Weah'),
    S('USA-13','Team Photo'), S('USA-14','Diego Luna'), S('USA-15','Malik Tillman'), S('USA-16','Christian Pulisic'),
    S('USA-17','Brenden Aaronson'), S('USA-18','Ricardo Pepi'), S('USA-19','Haji Wright'), S('USA-20','Folarin Balogun'),
  ],
  'UZB': [
    S('UZB-1','Emblem',true), S('UZB-2','Utkir Yusupov'), S('UZB-3','Farrukh Savfiev'), S('UZB-4','Sherzod Nasrullaev'),
    S('UZB-5','Umar Eshmurodov'), S('UZB-6','Husniddin Aliqulov'), S('UZB-7','Rustamjon Ashurmatov'), S('UZB-8','Khojiakbar Alijonov'),
    S('UZB-9','Abdukodir Khusanov'), S('UZB-10','Odiljon Hamrobekov'), S('UZB-11','Otabek Shukurov'), S('UZB-12','Jamshid Iskanderov'),
    S('UZB-13','Team Photo'), S('UZB-14','Azizbek Turgunboev'), S('UZB-15','Khojimat Erkinov'), S('UZB-16','Eldor Shomurodov'),
    S('UZB-17','Oston Urunov'), S('UZB-18','Jaloliddin Masharipov'), S('UZB-19','Igor Sergeev'), S('UZB-20','Abbosbek Fayzullaev'),
  ],
};

// Build flat index: id -> sticker info
const STICKER_MAP = {};
for(const team in STICKERS_BY_TEAM){
  for(const s of STICKERS_BY_TEAM[team]){
    STICKER_MAP[s.id.toUpperCase()] = { ...s, team };
  }
}
const ALL_IDS = Object.keys(STICKER_MAP);
const TOTAL = ALL_IDS.length;

// ═══════════════════════════════════════════════════════════
// STATE
// ═══════════════════════════════════════════════════════════
